"""update counter table

Revision ID: 8c975ec70296
Revises: 4ce365979924
Create Date: 2020-03-01 20:08:06.202797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c975ec70296'
down_revision = '4ce365979924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_counter_value', table_name='counter')
    op.create_index(op.f('ix_counter_value'), 'counter', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counter_value'), table_name='counter')
    op.create_index('ix_counter_value', 'counter', ['value'], unique=1)
    # ### end Alembic commands ###
