"""imagelist table

Revision ID: e3f5217ac392
Revises: ab24202692ae
Create Date: 2020-03-01 16:58:20.547545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f5217ac392'
down_revision = 'ab24202692ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_list_name'), 'image_list', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_list_name'), table_name='image_list')
    op.drop_table('image_list')
    # ### end Alembic commands ###
